services:
  database:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
    
  backend:
    build: ./backend
    container_name: backendCompose
    restart: always
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"
    
  frontend:
    build: ./frontend
    container_name: frontendCompose
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
           